### ISSUE TITLE
clone 代码到本地启动出错

### ISSUE THREAD

**Issue by gdshen95** [zythum/mama2#122]
```/Users/jellyshen/IdeaProjects/mama2/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:415
      throw new Error('"' + aSource + '" is not in the SourceMap.');
      ^

Error: "node_modules/browser-pack/_prelude.js" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/jellyshen/IdeaProjects/mama2/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:415:13)
    at SourceMapGenerator.<anonymous> (/Users/jellyshen/IdeaProjects/mama2/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/jellyshen/IdeaProjects/mama2/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
    at applySourceMap (/Users/jellyshen/IdeaProjects/mama2/node_modules/vinyl-sourcemaps-apply/index.js:23:15)
    at DestroyableTransform.uglify [as _transform] (/Users/jellyshen/IdeaProjects/mama2/node_modules/gulp-uglify/index.js:86:4)
    at DestroyableTransform.Transform._read (/Users/jellyshen/IdeaProjects/mama2/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/jellyshen/IdeaProjects/mama2/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/jellyshen/IdeaProjects/mama2/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/jellyshen/IdeaProjects/mama2/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_writable.js:227:5)
```

目前做法是注释了抛出异常的那一句（根本没有解决问题嘛((逃))，并没有影响正常解析。
而且这个问题很诡异地出现在，运行一段时间之后。。。不知道是不是我添加了一个seeker\_dilidili.js的缘故(seeker\_dilidili.js以及提交pr了)。

**Comment by zythum** [comment]
你看下，。估计是压缩的时候报错了。是不是和你引入的包有关？

**Comment by gdshen95** [comment]
这个问题现在复现不出来了😂
